version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: is-container 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - is-volume:/var/lib/postgresql/data
volumes:
  is-volume:
    driver: local
